<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSmcrt7m\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSmcrt7m/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSmcrt7m.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSmcrt7m\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSmcrt7m\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Smcrt7m',
    'container.build_id' => '1a8a1780',
    'container.build_time' => 1557132110,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSmcrt7m');
